### ISSUE TITLE
Podspec issue

### ISSUE THREAD

**Issue by pkania-as** [ZebraDevs/Zebra-Technologies-Printer-SDK#3]
Hello,

As podspec is not yet publicly available, I am trying to set path to podspec manually, like this

`
pod 'ZSDK_API', :podspec => 'https://github.com/ZebraDevs/Zebra-Technologies-Printer-SDK/blob/MPSDK-2066/ZSDK_API.podspec'
`

 but I get the following error: 

```
Analyzing dependencies
Fetching podspec for `ZSDK_API` from `https://github.com/ZebraDevs/Zebra-Technologies-Printer-SDK/blob/MPSDK-2066/ZSDK_API.podspec`
[!] Failed to load 'ZSDK_API' podspec:
[!] Invalid `ZSDK_API.podspec` file: syntax error, unexpected '<'
<!DOCTYPE html>
^
/masked/masked/masked/masked/ZSDK_API.podspec:9: syntax error, unexpected '<'
<html lang="en" data-color-mod...
^
/masked/masked/masked/masked/ZSDK_API.podspec:9: syntax error, unexpected local variable or method, expecting end-of-input
<html lang="en" data-color-mode="auto" data-light...
                ^~~~
.

 #  from /masked/masked/masked/masked/ZSDK_API.podspec:8
 #  -------------------------------------------
 #
 >  <!DOCTYPE html>
 #  <html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"  data-a11y-animated-images="system">
 #  ----
```

Could I ask you to check it out?
Thank you!

**Comment by jkimba3** [comment]
Fixed the issue with the podspec not being publicly available.  You can add the following to your podfile to import through Cocoapods: pod 'ZSDK_API', '~> 1.6.1069'

Please let us know if you have any further issues with installing it.  Thanks.

**Comment by pkania-as** [comment]
The `pod install` command started to work correctly, but when trying to compile the project, I get the error `Library not found for -lZSDK_API`

**Comment by jkimba3** [comment]
We are looking into this issue and will respond with any updates or fixes we find

**Comment by Cooparr** [comment]
Saw that there was a new release `1.6.1070`
Still getting the same `Library not found for -lZSDK_API` error

**Comment by grodriguesCP** [comment]
Hello, 

I have the same problem and I solved by changing the name of library inside xcframework from "ZSDK_API.a" to "libZSDK_API.a" and inside info.plist file.

But the lib is not working.
I make a successfully connection to printer but all the tasks/commands I have run on printer don't do nothing. 

I try to run the samples avaliable on docs and not work to.

@jkimba3 can you help ?
